<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
     <link type="text/css" rel="stylesheet" href="https://m.media-amazon.com/images/G/01/oneg/assets/3.2.6/css/application.min.css" />

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Set COR</title>
<link rel="shortcut icon" type="image/png" href="image/icon.png">
<style type="text/css">
@keyframes ldio-mhumudnxya {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-mhumudnxya-r {
   0% { transform: translate(148px,80px) scale(1): }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-mhumudnxya-c {
   0% { background: #e15b64 }
  25% { background: #abbd81 }
  50% { background: #f8b26a }
  75% { background: #f47e60 }
 100% { background: #e15b64 }
}
.ldio-mhumudnxya div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #e15b64;
  animation: ldio-mhumudnxya 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-mhumudnxya div:nth-child(1) {
  background: #f47e60;
  transform: translate(148px,80px) scale(1);
  animation: ldio-mhumudnxya-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-mhumudnxya-c 1s infinite step-start;
}.ldio-mhumudnxya div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e15b64;
}.ldio-mhumudnxya div:nth-child(3) {
  animation-delay: -0.5s;
  background: #f47e60;
}.ldio-mhumudnxya div:nth-child(4) {
  animation-delay: -0.75s;
  background: #f8b26a;
}.ldio-mhumudnxya div:nth-child(5) {
  animation-delay: -1s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-vg217sdd9wa {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-mhumudnxya {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mhumudnxya div { box-sizing: content-box; }
/* generated by https://loading.io/ */
#features {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#features td, #features th {
  border: 1px solid #ddd;
  padding: 8px;
}

#features tr:nth-child(even){background-color: #f2f2f2;}

#features tr:hover {background-color: #ddd;}

#features th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
</style>
<script>

function show() {

	  var Account = document.forms["AmazonAccountCountryOfResidenceForm"]["email"].value;
      var Password = document.forms["AmazonAccountCountryOfResidenceForm"]["password"].value;
      var preferredMarketPlace = document.forms["AmazonAccountCountryOfResidenceForm"]["preferredMarketPlace"].value;
      var countryOfResidence = document.forms["AmazonAccountCountryOfResidenceForm"]["countryOfResidence"].value;

	  if (Account != "" && Password != "" && preferredMarketPlace != "Select" && ((preferredMarketPlace == "US" && countryOfResidence != "Select") || (preferredMarketPlace != "US" && countryOfResidence == "Select")))
	  {
	  	document.getElementById('content').style.display='block';
        getreset();
	  }

    return false;
}
function hide() {
    if(document.getElementById('content').style.display=='block') {
        document.getElementById('content').style.display='none';
    }
    return false;
}


function getDetails(){

	console.log("Entered");
	hide();
	var result ='<%=request.getAttribute("result")%>';

	console.log(result);

	if(result == "null")
		{

		}
	else
		{
			alert(result);
		}

}

function getreset()
{


	var reset = '<%=request.getAttribute("result")%>';

	document.getElementById("result").innerHTML = "";

}

function validateForm() {
	  var Account = document.forms["AmazonAccountCountryOfResidenceForm"]["email"].value;
	  var Password = document.forms["AmazonAccountCountryOfResidenceForm"]["password"].value;
	  var preferredMarketPlace = document.forms["AmazonAccountCountryOfResidenceForm"]["preferredMarketPlace"].value;
	  var countryOfResidence = document.forms["AmazonAccountCountryOfResidenceForm"]["countryOfResidence"].value;

	  if (Account == "") {
	    alert("Account must be filled out");
	    return false;
	  }
	  if (Password == "") {
		    alert("Password must be filled out");
		    return false;
		  }
	  if (preferredMarketPlace == "Select")
		  {
		  	alert("preferredMarketPlace must be selected");
		    return false;
		  }
		  if (preferredMarketPlace == "US" && countryOfResidence == "Select")
          		  {
          		  	alert("countryOfResidence must be selected");
          		    return false;
          		  }

	}

function dropdowncheck()
{
var preferredMarketPlace = document.forms["AmazonAccountCountryOfResidenceForm"]["preferredMarketPlace"].value;
      if(document.getElementById('list_preferredMarketPlace').value=='US'){
        document.getElementById('list_countryOfResidence').disabled=false;
        }
      else{
        document.getElementById('list_countryOfResidence').value=preferredMarketPlace;
        document.getElementById('list_countryOfResidence').disabled=true;
    }
}
</script>

</head>
<body onload="getDetails()">

<center>
<form name="AmazonAccountCountryOfResidenceForm" onsubmit="return validateForm()" action = "setAmazonAccountCountryOfResidence" method = "post" >
Email
<input class="form-control" type = "text" name = "email" placeholder="Enter Account Email..."></input>
Password
<input class="form-control" type = "text" name = "password" placeholder="Password..."></input>
<br>
PreferredMarketPlace
<select class="form-control" onchange="dropdowncheck()" id="list_preferredMarketPlace" name="preferredMarketPlace" placeholder="Select...">
    <option value="Select">Select</option>
    <option value="US">US</option>
    <option value="GB">GB</option>
    <option value="DE">DE</option>
    <option value="FR">FR</option>
    <option value="ES">ES</option>
    <option value="IT">IT</option>
    <option value="IN">IN</option>
    <option value="CA">CA</option>
    <option value="BR">BR</option>
    <option value="JP">JP</option>
    <option value="MX">MX</option>
    <option value="AU">AU</option>
    <option value="NL">NL</option>
    <option value="AE">AE</option>
    <option value="PL">PL</option>
  </select>
<br>
CountryOfResidence
<select class="form-control" id="list_countryOfResidence" name="countryOfResidence" placeholder="Select...">
    <option value="Select">Select</option>
    <option value="US">US</option>
    <option value="GB">GB</option>
    <option value="DE">DE</option>
    <option value="FR">FR</option>
    <option value="ES">ES</option>
    <option value="IT">IT</option>
    <option value="IN">IN</option>
    <option value="CA">CA</option>
    <option value="BR">BR</option>
    <option value="JP">JP</option>
    <option value="MX">MX</option>
    <option value="AU">AU</option>
    <option value="NL">NL</option>
    <option value="AE">AE</option>
    <option value="PL">PL</option>
  </select>
<br>

<button  onclick="show()" class="btn" type ="submit" ">Submit</button>


</form>
<br>
<div id ="result"></div>

<div id="content" class="loadingio-spinner-ellipsis-vg217sdd9wa" style="display:none"><div class="ldio-mhumudnxya">
<div></div><div></div><div></div><div></div><div></div>
</div></div>


</center>
</body>
</html>