<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
     <link type="text/css" rel="stylesheet" href="https://m.media-amazon.com/images/G/01/oneg/assets/3.2.6/css/application.min.css" />

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Build Signer</title>
<link rel="shortcut icon" type="image/png" href="image/icon.png">
<style type="text/css">
@keyframes ldio-mhumudnxya {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-mhumudnxya-r {
   0% { transform: translate(148px,80px) scale(1): }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-mhumudnxya-c {
   0% { background: #e15b64 }
  25% { background: #abbd81 }
  50% { background: #f8b26a }
  75% { background: #f47e60 }
 100% { background: #e15b64 }
}
.ldio-mhumudnxya div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #e15b64;
  animation: ldio-mhumudnxya 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-mhumudnxya div:nth-child(1) {
  background: #f47e60;
  transform: translate(148px,80px) scale(1);
  animation: ldio-mhumudnxya-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-mhumudnxya-c 1s infinite step-start;
}.ldio-mhumudnxya div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e15b64;
}.ldio-mhumudnxya div:nth-child(3) {
  animation-delay: -0.5s;
  background: #f47e60;
}.ldio-mhumudnxya div:nth-child(4) {
  animation-delay: -0.75s;
  background: #f8b26a;
}.ldio-mhumudnxya div:nth-child(5) {
  animation-delay: -1s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-vg217sdd9wa {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-mhumudnxya {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mhumudnxya div { box-sizing: content-box; }
/* generated by https://loading.io/ */
#SignedBuilds {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#SignedBuilds td, #SignedBuilds th {
  border: 1px solid #ddd;
  padding: 8px;
}

#SignedBuilds tr:nth-child(even){background-color: #f2f2f2;}

#SignedBuilds tr:hover {background-color: #ddd;}

#SignedBuilds th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
</style>
<script>

function show() {
	var buildNumber = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["buildNumber"].value;
    	  var branchName = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["branchName"].value;
    	  var EnvironmentAndVersion_Dropdown = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["EnvironmentAndVersion_Dropdown"].value;
    	  var fireOSApkType_Dropdown = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["fireOSApkType_Dropdown"].value;

	  if (buildNumber != "" && fireOSApkType_Dropdown != "Select" && EnvironmentAndVersion_Dropdown != "Select" && branchName != "")
	  {
	  	document.getElementById('content').style.display='block';
     	getreset();
	  }


 return false;
}
function hide() {
    if(document.getElementById('content').style.display=='block') {
        document.getElementById('content').style.display='none';
        document.getElementById('result').style.display='none';
    }
    return false;
}


function getDetails(){

	console.log("Entered");
	hide();
	var result =<%=request.getAttribute("result")%>;

	console.log(result);


	if(result == "null" && buildname == "null")
		{

		}
	else
		{
			alert(result);

			//document.getElementById("result").innerHTML = result;

			var x = document.createElement("TABLE");
		    x.setAttribute("id", "SignedBuilds");
		    document.getElementById("result").appendChild(x);

		    for(var i=0;i<result.length;i++)
		    	{

		    	var rowtext = result[i];
		    	var rowtext1 = rowtext.split('-');
		    	console.log(rowtext1[0]);
		    	//var rowtext2 = rowtext.split('-')[1];
		    	console.log(rowtext1[1]);

			var tab = document.getElementById("SignedBuilds");
			var newrow = tab.insertRow(i);
			var newcell = newrow.insertCell(0);
			var newcell1 = newrow.insertCell(1);
			var newtext = document.createTextNode(rowtext1[0]);
			var a = document.createElement('a');
			var str = rowtext1[1];
			//var newtext1 = document.createTextNode(result[4]+" - "+str);
			var link = document.createTextNode(rowtext1[1]);
			var newtext1 = str;
			newcell.appendChild(newtext);
			a.appendChild(link);
			a.href = newtext1;
			newcell1.appendChild(a);

		    	}


		}

}

function getreset()
{


	var reset = '<%=request.getAttribute("result")%>';

	document.getElementById("result").innerHTML = "";

}
function validateForm() {
	  var buildNumber = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["buildNumber"].value;
	  var branchName = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["branchName"].value;
	  var EnvironmentAndVersion_Dropdown = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["EnvironmentAndVersion_Dropdown"].value;
	  var fireOSApkType_Dropdown = document.forms["downloadAlexaAPKAndSignInCodeSignerForm"]["fireOSApkType_Dropdown"].value;

	  if (buildNumber == "") {
		    alert("Enter Build Number");
		    return false;
		  }
	  if (branchName == "") {
            alert("Enter Branch Number");
          	return false;
          }

	  if (fireOSApkType_Dropdown == "Select") {
		    alert("FireOS Apk Type should be selected");
		    return false;
		  }

		  if (EnvironmentAndVersion_Dropdown == "Select") {
          		    alert("Environment And Version should be selected");
          		    return false;
          		  }
	}
</script>

</head>
<body onload="getDetails()">

<center>
<form name="downloadAlexaAPKAndSignInCodeSignerForm" onsubmit="return validateForm()" action = "downloadAlexaAPKAndSignInCodeSigner" method = "post" >
Build Number - Give 6 digit number excluding 2.2.
<input class="form-control" type = "text" name = "buildNumber" maxlength="6" placeholder="Enter Build Number..."></input>
Branch Name
<input class="form-control" type = "text" name = "branchName" maxlength="7" placeholder="Enter Branch Name..."></input>
<br>
Select Environment And Version
<select class="form-control" id="list_environment_version_Dropdown" name="EnvironmentAndVersion_Dropdown">
    <option value="Select">Select</option>
    <option value="All">All</option>
    <option value="Prod">Prod</option>
    <option value="Gamma">Gamma</option>
    <option value="Prod_Android">Prod_Android</option>
    <option value="Gamma_Android">Gamma_Android</option>
    <option value="Prod_Gamma_32">ProdGamma_32_Bit</option>
    <option value="Prod_Gamma_64">ProdGamma_64_Bit</option>
    <option value="Prod_Gamma_FireOS">ProdGamma_FireOS</option>
    <option value="Prod_32">Prod_32_Bit</option>
    <option value="Gamma_32">Gamma_32_Bit</option>
    <option value="Prod_64">Prod_64_Bit</option>
    <option value="Gamma_64">Gamma_64_Bit</option>
    <option value="Prod_FireOS">Prod_FireOS</option>
    <option value="Gamma_FireOS">Gamma_FireOS</option>

</select>
<br>
Select FireOS APK Type
<select class="form-control" id="list_fireOS_apkType" name="fireOSApkType_Dropdown">
    <option value="Select">Select</option>
    <option value="release">release</option>
    <option value="development">development</option>
</select>
<br>
<button  onclick="show();" class="btn" type ="submit" ">Submit</button>
<br>

</form>
<br>

<div id ="result"></div>

<div id="content" class="loadingio-spinner-ellipsis-vg217sdd9wa" style="display:none"><div class="ldio-mhumudnxya">
<div></div><div></div><div></div><div></div><div></div>
</div></div>


</center>
</body>
</html>