<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <link type="text/css" rel="stylesheet" href="https://m.media-amazon.com/images/G/01/oneg/assets/3.2.6/css/application.min.css" />

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Account Creation</title>
<link rel="shortcut icon" type="image/png" href="image/icon.png">
<style type="text/css">
@keyframes ldio-mhumudnxya {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-mhumudnxya-r {
   0% { transform: translate(148px,80px) scale(1): }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-mhumudnxya-c {
   0% { background: #e15b64 }
  25% { background: #abbd81 }
  50% { background: #f8b26a }
  75% { background: #f47e60 }
 100% { background: #e15b64 }
}
.ldio-mhumudnxya div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #e15b64;
  animation: ldio-mhumudnxya 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-mhumudnxya div:nth-child(1) {
  background: #f47e60;
  transform: translate(148px,80px) scale(1);
  animation: ldio-mhumudnxya-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-mhumudnxya-c 1s infinite step-start;
}.ldio-mhumudnxya div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e15b64;
}.ldio-mhumudnxya div:nth-child(3) {
  animation-delay: -0.5s;
  background: #f47e60;
}.ldio-mhumudnxya div:nth-child(4) {
  animation-delay: -0.75s;
  background: #f8b26a;
}.ldio-mhumudnxya div:nth-child(5) {
  animation-delay: -1s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-vg217sdd9wa {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-mhumudnxya {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mhumudnxya div { box-sizing: content-box; }
/* generated by https://loading.io/ */
#features {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#features td, #features th {
  border: 1px solid #ddd;
  padding: 8px;
}

#features tr:nth-child(even){background-color: #f2f2f2;}

#features tr:hover {background-color: #ddd;}

#features th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
#myProgress {
  width: 100%;
  background-color: #ddd;
}

#myBar {
  width: 10%;
  height: 30px;
  background-color: #04AA6D;
  text-align: center;
  line-height: 30px;
  color: white;
}
</style>
</head>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>

function show() {
	var email = document.forms["accountCreationForm"]["email"].value;
    var password = document.forms["accountCreationForm"]["password"].value;
    var start = document.forms["accountCreationForm"]["start"].value;
    var end = document.forms["accountCreationForm"]["end"].value;
    var preferredMarketPlace = document.forms["accountCreationForm"]["preferredMarketPlace"].value;

	  if (email != "" && password != "" && start != "" && end != "" && preferredMarketPlace != "Select")
	  {
	  	document.getElementById('content').style.display='block';
      	getreset();
	  }

  return false;
}
function hide() {
    if(document.getElementById('content').style.display=='block') {
        document.getElementById('content').style.display='none';
    }
    return false;
}


function getDetails(){

	console.log("Entered")
	hide();
	var result ='<%=request.getAttribute("result")%>';
	var progress ='<%=request.getAttribute("progressvalue")%>';

	console.log(result);

	if (result == "null")
		{

		}
	else
		{
			alert(result);
			document.getElementById("result").innerHTML = "<a href = \"downloadaccountcreationfile.jsp\">Download</a>";
			document.getElementById("myText").innerHTML = number;
		}

}

function getreset()
{
	var reset = '<%=request.getAttribute("result")%>';
	var progress ='<%=request.getAttribute("progressvalue")%>';

	document.getElementById("result").innerHTML = "";
	document.getElementById("myText").innerHTML = "";
}

function validateForm() {
	  var email = document.forms["accountCreationForm"]["email"].value;
      	  var password = document.forms["accountCreationForm"]["password"].value;
      	  var start = document.forms["accountCreationForm"]["start"].value;
      	  var end = document.forms["accountCreationForm"]["end"].value;
      	  var preferredMarketPlace = document.forms["accountCreationForm"]["preferredMarketPlace"].value;

	  if (email == "") {
	    alert("Account must be filled out");
	    return false;
	  }
	  if (password == "") {
		    alert("Password must be filled out");
		    return false;
		  }
	  if (start == "") {
		    alert("Starting sequence must be filled out");
		    return false;
		  }
	  if (end == "") {
		    alert("Ending sequence must be filled out");
		    return false;
		  }
	  if (preferredMarketPlace == "Select") {
            alert("Status must be selected");
            return false;
          }
}

</script>

<body onload="getDetails()">

<center>
<form name="accountCreationForm" onsubmit="return validateForm()" action = "createTestAccounts" method = "post" >

Account Email
<input class="form-control" type = "text" name = "email" placeholder="Ex: alias+text"></input>
Password
<input class="form-control" type = "text" name = "password" placeholder="Password..."></input>
Sequence
<input class="form-control" type = "text" name = "start" placeholder="Ex: 1"></input>
<br>
<input class="form-control" type = "text" name = "end" placeholder="Ex: 2"></input>
<br>
Country - Always select None (DE and JP is under implementation)
<select class="form-control" id="list_preferredMarketPlace" name="preferredMarketPlace" placeholder="Select...">
    <option value="Select">Select</option>
    <option value="NONE">NONE</option>
    <option value="US">US</option>
    <option value="GB">GB</option>
    <option value="AU">AU</option>
    <option value="MX">MX</option>
    <option value="CA">CA</option>
    <option value="DE">DE</option>
    <option value="JP">JP</option>
  </select>
<br>
<button id="submitButton" onclick="show();" class="btn" type ="submit" ">Submit</button>


</form>
<br>
<div id ="result"></div>
<br>
<div>
 <p>Check for the subscribed mail list before running the script. <a href ="https://email-list.corp.amazon.com/email-list/email-list.mhtml?action=expand-user&name=arnach">See Here</a> <span id="progressText"></span></p>
</div>
<br>
<div id="content" class="loadingio-spinner-ellipsis-vg217sdd9wa" style="display:none"><div class="ldio-mhumudnxya">
<div></div><div></div><div></div><div></div><div></div>
</div></div>

</center>
</body>
</html>