<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
     <link type="text/css" rel="stylesheet" href="https://m.media-amazon.com/images/G/01/oneg/assets/3.2.6/css/application.min.css" />

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Voice Purchasing</title>
<link rel="shortcut icon" type="image/png" href="image/icon.png">
<style type="text/css">
@keyframes ldio-mhumudnxya {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-mhumudnxya-r {
   0% { transform: translate(148px,80px) scale(1): }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-mhumudnxya-c {
   0% { background: #e15b64 }
  25% { background: #abbd81 }
  50% { background: #f8b26a }
  75% { background: #f47e60 }
 100% { background: #e15b64 }
}
.ldio-mhumudnxya div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #e15b64;
  animation: ldio-mhumudnxya 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-mhumudnxya div:nth-child(1) {
  background: #f47e60;
  transform: translate(148px,80px) scale(1);
  animation: ldio-mhumudnxya-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-mhumudnxya-c 1s infinite step-start;
}.ldio-mhumudnxya div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e15b64;
}.ldio-mhumudnxya div:nth-child(3) {
  animation-delay: -0.5s;
  background: #f47e60;
}.ldio-mhumudnxya div:nth-child(4) {
  animation-delay: -0.75s;
  background: #f8b26a;
}.ldio-mhumudnxya div:nth-child(5) {
  animation-delay: -1s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-vg217sdd9wa {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-mhumudnxya {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mhumudnxya div { box-sizing: content-box; }
/* generated by https://loading.io/ */
#features {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#features td, #features th {
  border: 1px solid #ddd;
  padding: 8px;
}

#features tr:nth-child(even){background-color: #f2f2f2;}

#features tr:hover {background-color: #ddd;}

#features th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
</style>
<script>

function show() {

	 var Account = document.forms["voicePurchasingToggleForm"]["email"].value;
     	  var Password = document.forms["voicePurchasingToggleForm"]["password"].value;

     	  var toggle = document.forms["voicePurchasingToggleForm"]["VPToggle"].value;
	  if (Account != "" && Password != "" && toggle != "Select")
	  {
	  	document.getElementById('content').style.display='block';
        getreset();
	  }

    return false;
}
function hide() {
    if(document.getElementById('content').style.display=='block') {
        document.getElementById('content').style.display='none';
    }
    return false;
}


function getDetails(){

	console.log("Entered");
	hide();
	var result ='<%=request.getAttribute("result")%>';

	console.log(result);

	if(result == "null")
		{

		}
	else
		{
			alert(result);
		}

}

function getreset()
{


	var reset = '<%=request.getAttribute("result")%>';

	document.getElementById("result").innerHTML = "";

}

function validateForm() {
	  var Account = document.forms["voicePurchasingToggleForm"]["email"].value;
	  var Password = document.forms["voicePurchasingToggleForm"]["password"].value;
	  var toggle = document.forms["voicePurchasingToggleForm"]["VPToggle"].value;
	  if (Account == "") {
	    alert("Account must be filled out");
	    return false;
	  }
	  if (Password == "") {
		    alert("Password must be filled out");
		    return false;
		  }
	  if (toggle == "Select")
		  {
		  	alert("Status must be selected");
		    return false;
		  }

	}
</script>

</head>
<body onload="getDetails()">

<center>
<form name="voicePurchasingToggleForm" onsubmit="return validateForm()" action = "voicePurchasingToggle" method = "post" >
Account Email
<input class="form-control" type = "text" name = "email" placeholder="Enter Account Email..."></input>
Password
<input class="form-control" type = "text" name = "password" placeholder="Password..."></input>
<br>
Status
<select class="form-control" id="list_status" name="VPToggle" placeholder="Select...">
    <option value="Select">Select</option>
    <option value="Check">Check And Enable</option>
    <option value="Disable">Disable</option>

  </select>
<br>
<button  onclick="show()" class="btn" type ="submit" ">Submit</button>


</form>
<br>
<div id ="result"></div>

<div id="content" class="loadingio-spinner-ellipsis-vg217sdd9wa" style="display:none"><div class="ldio-mhumudnxya">
<div></div><div></div><div></div><div></div><div></div>
</div></div>


</center>
</body>
</html>